project:
  type: website
  output-dir: docs

website:
  title: "Research, Analysis, and Visual Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tutorials"
        href: tutorials/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Zobaer Ahmed"

format:
  html:
    theme:
      light: flatly
      dark:  darkly
    toc: true
    page-layout: full
    mainfont: Times New Roman 
    font-size: 14px
    
editor: source


