---
title: "Climate change risk perceptions and agricultural adaptation strategies in vulnerable riverine char islands of Bangladesh"
type: "article"
author: "Zobaer Ahmed, Gauri S. Guha, Aaron M. Shew, G.M. Monirul Alam"
year: "2021"
publication: "Land Use Policy"
doi: "https://doi.org/10.1016/j.landusepol.2021.105295"
toc: false
categories:
  - Climate change 
  - Risk perception index
  - Adaptation strategies
  - Riverine char dwellers
  - Agricultural adaptation
---

## Citation (APA 7)

> Ahmed, Z., Guha, G. S., Shew, A. M., & Alam, G. M. (2021). Climate change risk perceptions and agricultural adaptation strategies in vulnerable riverine char islands of Bangladesh. *Land Use Policy*, 103, 105295.

## Abstract

Farmers in the riverine char islands of Bangladesh are frequently affected by climate change due to their proximity to the river and heavy reliance on agriculture for their livelihoods. The present study evaluates char dwellers’ risk perceptions and agricultural adaptations to climate change. Survey data were collected from 98 households, and focus group discussions were conducted using a semi-structured questionnaire from Rydas Bari char under the Gaibandha District of Bangladesh. A standardized risk perception index was created using a four-point Likert scale against sixteen climatic events. In addition, a binary logit model was used to estimate the influence of socioeconomic characteristics of sample households on the decision to choose climate change adaptation strategies. Findings suggest that droughts, river erosion, and floods are the major climatic risks perceived by char dwellers. Additionally, results from a climate vulnerability index portray similar findings that char respondents are more exposed to diverse climatic hazards. The study further investigates local adaptation mechanisms in agriculture with regards to major climatic events. In response to the existing climate change risks, the char inhabitants employ several adaptation strategies in agriculture such as implementing new or alternative farming practices, changing planting times, and cultivating short-duration varieties. The llogit analysis suggests that household age, family size, annual income, farm size, farm ownership and farming experience have a significant influence on farmers' adaptation choices. Household access to education, early warning by extension agents, information on improved agricultural technologies, access to off-farm sources of income and incorporating char people during policy design can effectively enhance farmers’ resilience and help reduce vulnerability.