---
title: "An examination of thematic research, development, and trends in remote sensing applied to conservation agriculture"
Type: "Article"
author: "Zobaer Ahmed, Aaron Shew, Lawton Nalley, Michael Popp, V. Steven Green, Kristofor Brye"
Year: "2024"
Publication: "International Soil and Water Conservation Research"
doi: "https://doi.org/10.1016/j.iswcr.2023.04.001"
toc: false
categories:
  - Remote sensing
  - Conservation agriculture
  - Classification algorithm
  - Spatial resolution
  - Satellite
  - Spectral indices
  - PRISMA
---

## Citation (APA 7)

> Ahmed, Z., Shew, A., Nalley, L., Popp, M., Green, V. S., & Brye, K. (2024). An examination of thematic research, development, and trends in remote sensing applied to conservation agriculture. *International Soil and Water Conservation Research*, 12(1), 77–95. 

## Abstract

Conservation agriculture seeks to reduce environmental degradation through sustainable management of agricultural land. Since the 1990s, agricultural research has been conducted using remote sensing technologies; however, few previous reviews have been conducted focused on different conservation management practices. Most of the previous literature has focused on the application of remote sensing in agriculture without focusing exclusively on conservation practices, with some only providing a narrative review, others using biophysical remote sensing for quantitative estimates of the bio-geo-chemical-physical properties of soils and crops, and few others focused on single agricultural management practices. This paper used the preferred reporting items for systematic review (PRISMA) methodology to examine the last 30 years of thematic research, development, and trends associated with remote sensing technologies and methods applied to conservation agriculture research at various spatial and temporal scales. A set of predefined key concepts and keywords were applied in three databases: Scopus, Web of Science, and Google Scholar. A total of 188 articles were compiled for initial examination, where 68 articles were selected for final analysis and grouped into cover crops, crop residue, crop rotation, mulching, and tillage practices. Publications on conservation agriculture research using remote sensing have been increasing since 1991 and peaked at 10 publications in 2020. Among the 68 articles, 94% used a pixel-based, while only 6% used an object-based classification method. Prior to 2005, tillage practices were abundantly studied, then crop residue was a focused theme between 2004 and 2012. From 2012 to 2020, the focus shifted again to cover crops. Ten spectral indices were used in 76% of the 68 studies. This examination offered a summary of the new potential and identifies crucial future research needs and directions that could improve the contribution of remote sensing to the provision of long-term operational services for various conservation agriculture applications.